@extends('layouts.main')


@section('content')
	<div class="wrapper gray-wrapper">
      <div class="container inner">
        <h2 class="heading text-center">Privacy Policy</h2>
        <div class="space20"></div>
        <div class="row">

          <div class="col-lg-10 ">
            <p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>MEDSPA.ONE , (&ldquo;<strong>MEDSPA.ONE&nbsp;</strong>&quot;, &ldquo;<strong>we</strong>&rdquo; or &quot;<strong>us</strong>&quot;) respects the privacy of the customers and physicians using its Site (available at <a href="{{ route('terms') }}"><span style="color:#0B61FF;text-decoration:none;">&nbsp;Terms and Conditions</span></a>) (collectively, &ldquo;<strong>Users</strong>&rdquo; or &ldquo;<strong>you</strong>&rdquo;), and is committed to protect the personal information that its Users share with it. We believe that you have a right to know our practices regarding the information we may collect, use or disclose when you visit or use our Site or Services. MEDSPA.ONE &nbsp;provides this Privacy Policy (&quot;<strong>Privacy Policy</strong>&quot;) to help you make an informed decision about whether to use or continue using our Site or Services. Capitalized terms not defined here have the meaning ascribed to them in our Terms (available at <a href="{{ route('terms') }}"><span style="color:#0B61FF;text-decoration:none;">Terms and Conditions</span></a>).</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>1. Your Consent (PLEASE READ CAREFULLY)</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>You accept and agree to be bound by this Privacy Policy and our Terms (available at <a href="{{ route('terms') }}"><span style="color:#0B61FF;text-decoration:none;">Terms and Conditions</span></a>) by accessing or using the Site or the Services. The Site and Services are available only to people who are at least eighteen (18) years old and possess the legal capacity to form a binding agreement with MEDSPA.ONE . IF YOU DO NOT HAVE SUCH LEGAL CAPACITY, OR IF YOU DO NOT AGREE TO ABIDE BY OR BE BOUND BY THIS PRIVACY POLICY OR THE TERMS, THEN DO NOT ACCESS THE SITE OR USE THE SERVICES.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>2. Children&#39;s Privacy</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>We do not intend to and do not knowingly collect Personal Information (as defined below) from children under the age of eighteen (18). We reserve the right to request proof of age at any stage so that we can verify that children under the age of eighteen (18) are not using the Services. If we learn that we collected Personal Information from children under the age of eighteen (18) we will delete that information as quickly as possible. Please contact us at info@MEDSPA.ONE .com if you have reasons to suspect that we collected Personal Information from children under the age of eighteen (18) and we will delete that information as quickly as possible. It is hereby clarified that the Submissions/Physician Submissions should not include information regarding children under the age of eighteen (18).</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>3. Which information we may collect on our Users?</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>We may collect two types of information from our Users:</span></p>

<ol>
  <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>The first type of information is non-identifiable and anonymous information (&ldquo;<strong>Non-personal Information</strong>&rdquo;). <strong>We are not aware of the identity of the User from whom we have collected the Non-personal Information.</strong> Non-Personal Information is any unconcealed information which does not enable identification of an individual User, and which is available to us while such User is accessing or using the Site or Services. Non-personal Information which is being gathered consists of technical information, behavioral information and aggregated information, and may contain, among other things, the activity of the User on the Site or Services, User&#39;s &#39;click-stream&#39; or searches on the Site, heatmaps, referring / exit pages and URLs, type and version of browser and keyboard language, the hardware specifications of the User&#39;s device (including screen resolution and screen orientation), time spent on various pages of the Site, etc.</span>

    <ol>
      <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>The second type of information is individually identifiable information (&ldquo;<strong>Personal Information</strong>&rdquo;). <strong>This information may identify an individual or may be of a private and/or sensitive nature.</strong></span>

        <ul>
          <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Users of the Site may automatically provide their IP address (or Mac Address, as applicable) mainly for enhancing the User&rsquo;s experience and for geo-location and security purposes as further detailed below.</span></li>
          <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Users who are interested in opening an Account are required to provide the following details: full name, country, zip code, e-mail address, date of birth, gender, general or specific areas of interest (e.g. upper/lower body, etc.), categories of interest (e.g. cosmetic surgery, dermatology, plastic surgery, body contouring etc.) and a password. The Users may also choose to provide us with the following details: ethnicity or specific procedure interest.</span></li>
          <li><strong><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Alternatively</span></strong><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>, you can open an Account by integrating your existing third party accounts (such as, Facebook) (&quot;<strong>Social Network Account</strong>&quot;) with your Account. If you authorize such integration, then certain information contained in your Social Network Account may be transmitted into your Account (e.g. log-in information, your public profile, profile picture, list of friends and followers, likes/dislikes, number of views or other information which is detailed in the notice which appears during the integration process with your Social Network Account).</span></li>
          <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Using the Services may generate Personal Information, including without limitation: articles saved by the User before or after the log-in or registration process, information the User provides while using the Interactive Areas, including interactions with other Users (if such function is made available by MEDSPA.ONE ).</span></li>
          <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>The Services include a feature that enables Users to find and contact physicians (usually those located in the User&#39;s geographic area). When using this feature, you voluntarily provide the physician with your full name, email address, telephone number and your desired treatment.</span></li>
          <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>You may voluntarily provide Personal Information in your Submissions/Physician Submissions or when you fill the Contact Form on our Site.</span></li>
          <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>When a physician opens an Account, he/she will be required to use certain online payment methods which require him/her to provide to the online payment service providers certain Personal Information (such as, a credit card number and other related billing information).</span></li>
        </ul>
      </li>
    </ol>
  </li>
</ol>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>As long as any Non-Personal Information is connected or linked to any Personal Information, we treat it as Personal Information. <strong>We do not collect any Personal Information from you or related to you without your approval. Your approval is obtained, when you agree to our Terms and the Privacy Policy upon accessing or using our Site or Services.</strong></span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>4. How Do We Collect Information on Our Users?</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>We collect and store information, either independently or through the help of third-party service providers when you use the Site or Services and when you voluntarily disclose information on the Site. By way of example, when you open an Account, fill out the Contact Form, use the Interactive Areas or provide any information with your Submissions/Physician Submissions; we may collect and save such information. Please note that your Submission/Physician Submissions, especially those uploaded or shared within the Interactive Areas are non-confidential, become publicly available and may be collected, used or redistributed by others through the internet and other media channels.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>5. What are the Purposes of the Collection of Information?</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Non-personal Information and Personal Information are used for statistical and research purposes and allow us to improve the quality of the Site and Services (e.g. discovering User preferences and trends allows us to customize and enhance our Services) and offer future commercial services. Personal Information is also collected in order to:</span></p>

<ul>
  <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Send Users commercial content or advertisements.</span></li>
  <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Verify the User&#39;s identity when signing in to the Site or Services, as well as verifying a User&#39;s identity for the purpose of dealing with inappropriate interactions of Users and/or fraudulent use of our Services.</span></li>
  <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Be able to contact Users for the purpose of providing them with technical assistance and support.</span></li>
  <li><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Enable our Users to find and contact Physicians</span></li>
</ul>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>6. Transferring Information between Jurisdictions</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>The MEDSPA.ONE &nbsp;Site and Services are hosted in the United States and are mainly directed to Users in the United States. If you are a User accessing the Site from the European Union, Asia, or any other region with laws or regulations governing personal data collection, use, and disclosure, that differ from United States laws, please be advised that through your continued use of the Site, you are transferring your personal information to the United States and you consent to that transfer.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>7. Sharing Information with Third Parties</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>We may share certain information we collect from you with third parties (in the U.S. or in other countries) (i) for the purpose of processing or storing your information on our behalf; and (ii) for commercial purposes. You may choose to limit or prevent the sharing of certain Personal Information with third parties in the settings of your Account.</span></p>

<p style='margin:0in;margin-bottom:12.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'> </span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>In addition, we may share Personal Information in the following cases:</span></strong><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>&nbsp;(a) to satisfy any applicable law, regulation, legal process, subpoena or governmental request; (b) to enforce this Privacy Policy or the Terms, including investigation of potential violations thereof; (c) to detect, prevent, or otherwise address fraud, security or technical issues; (d) to respond to User&#39;s support requests; (e) to respond to claims that any content available on the Services violates the rights of third-parties; (f) to respond to claims that contact information (e.g. name, e-mail address, etc.) of a third-party has been posted or transmitted without their consent or as a form of harassment; (g) to protect the rights, property, or personal safety of MEDSPA.ONE , MEDSPA.ONE &nbsp;Representatives, our Users, or the general public; (h) when MEDSPA.ONE &nbsp;is undergoing any change in control, including by means of merger, acquisition or purchase of all or substantially all of its assets; (i) to collect, hold and/or manage your Personal Information through MEDSPA.ONE&rsquo;s authorized third parties service providers (including, as applicable, their affiliates as necessary to provide us with the requested services), as reasonable for business purposes, which may be located in a country that does not have the same data protection laws as your jurisdiction; (j) to store or process your Personal Information through MEDSPA.ONE&rsquo;s affiliated companies, which may be located in a country that does not have the same data protection laws as your jurisdiction. MEDSPA.ONE &nbsp;requires its affiliated entities to agree to processing your Personal Information in compliance with our Privacy Policy; (k) to enable payment through certain online payment services; and/or (m) pursuant to your explicit approval prior to the disclosure. For avoidance of doubt, MEDSPA.ONE &nbsp;may transfer and disclose <em>Non-personal Information</em> to third parties at its own discretion.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>8. Deletion or Modification of Personal Information</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>If for any reason you wish to delete or modify your Personal Information you can do so within the settings of your Account. In the event that you wish to modify or cancel your Account you may close your Account using the settings or you can send us an e-mail of your request to: to support@MEDSPA.ONE .com, and we will make reasonable efforts to modify or delete any such Personal Information pursuant to any applicable privacy laws. Note that unless you instruct us otherwise we may retain and use your Personal Information after termination of your Account, for as long as reasonably required for the purposes of which such Personal Information was collected, including without limitation, for future analytics and analysis, in order to comply with our legal or business requirements or obligations, to resolve disputes, to enforce our Terms or Privacy Policy and/or to enable Users to reinstate their Account, all as permitted under any applicable privacy laws. <strong>&nbsp;Aggregate and/or anonymous information derived from your Account and/or use of the Service may remain on our servers indefinitely.</strong></span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>9. Physicians Payment</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Please see Section 5 of the Terms. The service provider&#39;s terms of use and privacy policy, not our Terms and Privacy Policy, govern your use of the online payment services. The information they collect about you should be specified in such documents.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>10. Our Commitment to Data Security</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>We take reasonable physical, managerial and technical measures to maintain the security and integrity of our Users&#39; information, our Site and Services and prevent unauthorized access or use through generally accepted industry standard technologies and internal procedures. To protect your privacy and security, we take reasonable steps (such as requesting a unique password) to verify your identity when you log-in to your Account and/or our Services. You are responsible for maintaining the secrecy of your unique password and Account information at all times. Your Personal Information is contained behind secured networks and is only accessible by a limited number of persons who have special access rights to such systems, and are required to keep the information confidential. In addition, all sensitive/credit information you supply is encrypted via Secure Socket Layer (SSL) technology. We implement a variety of security measures when our Users enter, submit, or access their information in order to maintain the safety of our Users&#39; Personal Information. Our Users&#39; Information is hosted on the Azure Cloud servers which provide advanced strict security standards. If we learn of a security breach, then we may attempt to notify you electronically so that you can take appropriate protective steps. We may post a notice on our Site if a security breach occurs. Depending on where you live, you may have a legal right to receive notice of a security breach in writing. Please note, however, that there are inherent risks in transmission of information over the Internet or other methods of electronic storage and we cannot guarantee that unauthorized access or use of your Personal Information will never occur. WE WILL NOT BE RESPONSIBLE OR LIABLE FOR UNAUTHORIZED ACCESS, HACKING, OR OTHER SECURITY INTRUSIONS OR THE THEFT, DELETION, CORRUPTION, DESTRUCTION, DAMAGE, OR LOSS OF ANY DATA OR INFORMATION.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>11. Direct Marketing and Advertisements</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Direct Marketing: You hereby agree that we may use the contact details you provided us with for the purpose of offering you products or services which may interest you, or send to you other marketing materials. You may withdraw your consent by sending us a notice to the following email: support@MEDSPA.ONE .com or alternatively following the opt-out instructions for removing yourself from our mailing list which are available in the commercial materials transmitted to you. Advertisements: When using our Site or Services, you may receive or be exposed to advertisements and commercials from third party advertisers and/or our authorized service providers and/or vendors. By clicking the advertisements or commercials you may be transferred to a website of an advertiser or receive any other messages, information or offers from the advertiser and/or from others. Note that if you click on any of these advertisements, these advertisers may use web-tracking technologies to collect data regarding advertisement performance, your interaction with such ads and your interests (which may include, Non-personal and/or Personal Information about you) in order to serve you advertisements and for the legitimate business interests of such third parties&#39; ad networks. We recommend that you review the terms of use and privacy policy of any advertiser with which you are interacting, since their privacy policy, not ours, will apply to any of those interactions.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>12. Third Party Service Providers</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>We may be using third party software or service in order to collect, host, store and/or process information. We use commercially reasonable efforts to engage with third parties that post a privacy policy governing their collection, processing and use of Non-personal and Personal Information: Google Analytics which privacy policy can be found at <a href="http://www.google.com/policies/privacy/partners/"><span style="color:#0B61FF;text-decoration:none;">http://www.google.com/policies/privacy/partners/</span></a>, and at <a href="http://www.google.com/intl/en/analytics/privacyoverview.html"><span style="color:#0B61FF;text-decoration:none;">http://www.google.com/intl/en/analytics/privacyoverview.html</span></a>. We do not control third party service providers. Please read their terms of use and privacy policies to better understand their privacy practices.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>13. Account Display Options</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Your Account default settings allow us to display to other Users of the Site or Services information contained in your Account (including your Personal Information). In order to edit your display settings, you can log-in to the settings of your Account and choose which information will be displayed to others.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>14. Links to Third Party Websites or Services</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Please see Section 9 of the Terms. Most of the linked sites or services provide legal documents, including terms of use and privacy policy, governing their use. The information they collect about you should be specified in such documents.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>15. Cookies and Other Tracking Technologies</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>When you access or use our Site, we or our third party service providers may use industry-wide technologies such as &quot;cookies&quot; or other similar technologies, which store certain local information on your computer (&quot;Cookies&quot;) and/or track User usage patterns. Cookies allow the collection of Non-personal Information such as the different pages viewed by a User within Site, the duration of the browsing, etc. The cookies enable, inter alia, automatic activation of certain features and make the User&rsquo;s experience and usage simpler, more relevant, convenient and effortless. We and our third party service providers may use both session Cookies (which expire once the User closes the browser) and persistent Cookies (which stay on the User&#39;s browser and may be used by the browser on subsequent visits to the Site, unless deleted by the User). Most browsers will allow you to erase cookies from your computer&#39;s hard drive or from you device, block acceptance of cookies, or receive a warning before a cookie is stored. In order to erase or disable the Cookies you may use the settings of your browser. However, if you block or erase cookies our Services (and your User experience) may be limited.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>16. HIPAA Compliance</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>The combination of Personal Information with health related information is subject to special rules under the Health Insurance Portability and Accountability Act of 1996 (&quot;<strong>HIPAA</strong>&quot;). Physicians must also follow all HIPAA Privacy Rule and applicable state privacy requirements and must refrain from uploading, posting or submitting personal medical data which might be considered as protected health information, unless such uploading, posting or Physician Submission would be allowed under those laws and regulations and the Physician has obtained the necessary and appropriate authorization and consents. We will not assume any liability in this respect. Determination of whether inforamtion to be included in a Physician Submission is protected health information and/or other medical information protected by the HIPAA Privacy Rule and/or other sate laws and regulations is the sole responsiblity of the Physician. Obtaining the appropriate authorization consent is the sole responsibility of the Physician. By uploading, posting or submitting information, the Physician respresents and warrants that the Physician can upload, post or submit such information in full Compliance with the HIPAA Privacy Rule and other state laws and regulations. We will not asume any liability in this respect. Your Submissions, especially those uploaded or shared within the Interactive Areas are non-confidential, become publicly available and may be collected, used or redistributed by others through the internet and other media channels and are then not subject to the protections of the HIPAA Privacy Rule. The Services include a feature enabling Users to find and contact Physicians. The information provided to the physician through this feature is not used by MEDSPA.ONE &nbsp;in any other manner other than for the purpose of transmitting such information to the physician. Our Users hereby agree to keep all health information strictly between themselves and the applicable physician and not to share such information through the feature, the Site or the Service.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>17. Changes to the Privacy Policy</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>Please see Section 15 of the Terms.</span></p>

<p style='margin:0in;margin-bottom:6.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:28px;font-family:"Helvetica Neue";color:black;'>18. Got any Questions?</span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'>If you have any questions (or comments) concerning this Privacy Policy, you are most welcome to send us an email to the following address: info@MEDSPA.ONE and we will make an effort to reply within a reasonable timeframe.</span></p>

<p style='margin:0in;margin-bottom:12.0pt;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-size:21px;font-family:"Helvetica Neue";color:black;'> </span></p>

<p style='margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:"Calibri",sans-serif;'>
  <br>
</p>

          </div>
          <!-- /column -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->
  </div>
@endsection